name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Executa a cada push na branch main (mude para master se for o caso)

# Permissões necessárias para publicar no GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Cancela builds anteriores em andamento para a mesma branch/pages deploy
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Instalar dependências
        run: npm ci

      - name: Executar Build
        run: npm run build

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v4

      - name: Fazer upload do artefato
        uses: actions/upload-pages-artifact@v3
        with:
          # A pasta onde o Vite gerou o app estático pré-renderizado
          path: './dist/client'

      - name: Deploy no GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
